// Auto-generated by blockchain/scripts/contractDeployment.js
// Keep this file committed so frontend/backend share the same contract address.
export const CONTRACT_NAME = "DocumentVault";
export const contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
export const HARDHAT_LOCALHOST_CHAIN_ID = 31337;
export const LAND_REGISTRY_VERSION = "v2-history-transfer";
const contractConfig = { CONTRACT_NAME, contractAddress, HARDHAT_LOCALHOST_CHAIN_ID, LAND_REGISTRY_VERSION };
export default contractConfig;
