const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function deployContract(contractName = "DocumentVault") {
  console.log(`[deploy] Starting deployment for ${contractName}...`);

  await hre.run("compile");

  try {
    await hre.artifacts.readArtifact(contractName);
  } catch (error) {
    throw new Error(
      `[deploy] Artifact for "${contractName}" not found. Check contract name and run "npm run compile" in blockchain/.`
    );
  }

  const factory = await hre.ethers.getContractFactory(contractName);
  const contract = await factory.deploy();
  await contract.deployed();

  const address = contract.address;
  console.log(`[deploy] ${contractName} deployed at: ${address}`);

  const provider = hre.ethers.provider;
  const code = await provider.getCode(address);
  if (!code || code === "0x") {
    throw new Error(`[deploy] Contract code not found at ${address}`);
  }

  // Persist frontend runtime config so UI points to the latest deployed address.
  const frontendConfigPath = path.resolve(
    __dirname,
    "../../frontend/src/contract/contractconfig.js"
  );
  const artifactPath = path.resolve(
    __dirname,
    `../artifacts/contracts/${contractName}.sol/${contractName}.json`
  );
  const frontendAbiPath = path.resolve(
    __dirname,
    "../../frontend/src/contract/abi.json"
  );

  const configFile = `// Auto-generated by blockchain/scripts/contractDeployment.js
// Keep this file committed so frontend/backend share the same contract address.
export const CONTRACT_NAME = "${contractName}";
export const contractAddress = "${address}";
export const HARDHAT_LOCALHOST_CHAIN_ID = 31337;
export const LAND_REGISTRY_VERSION = "v2-history-transfer";
const contractConfig = { CONTRACT_NAME, contractAddress, HARDHAT_LOCALHOST_CHAIN_ID, LAND_REGISTRY_VERSION };
export default contractConfig;
`;

  fs.writeFileSync(frontendConfigPath, configFile, "utf8");
  console.log(`[deploy] Updated frontend config: ${frontendConfigPath}`);

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  fs.writeFileSync(frontendAbiPath, JSON.stringify(artifact.abi, null, 2), "utf8");
  console.log(`[deploy] Synced ABI to frontend: ${frontendAbiPath}`);

  return { contractName, address };
}

module.exports = { deployContract };

